#!/usr/bin/env bash

# is_displayPort_1_monitor_connected=$(xrandr --query | grep 'DisplayPort-1 connected')
# is_hdmi_monitor_connected=$(xrandr --query | grep 'HDMI-A-0 connected')


polybar dell-monitor 2>~/.config/polybar/logs/dell-monitor.log &
